// Trilingual content for the public landing page (/welcome) and its product demo.
// Kept separate from the app-UI dictionary (i18n.js) because this is marketing
// copy, edited on its own cadence. Landing.jsx and ProductDemo.jsx read
// LANDING[lang] (falling back to English). Proper nouns — scheme names, hospital
// and food names — stay in their real-world form on purpose.

export const LANDING = {
  en: {
    nav: { features: 'Features', safety: 'Safety', how: 'How it works', languages: 'Languages' },
    login: 'Log in',
    getStarted: 'Get started',
    getStartedFree: 'Get started free',
    watchDemo: 'Watch demo',
    createProfile: 'Create your free profile',
    beta: 'Free during our private beta',
    heroTitle: 'A caring companion for every step of your',
    heroAccent: 'pregnancy',
    heroSub: 'PoshanMitra AI guides expecting mothers in India with a friendly AI companion, daily nutrition, government schemes, nearby hospitals and safety-first care — in English, हिंदी and मराठी.',
    trust: ['3 languages', 'Safety-first design', 'Data stays on your device'],
    statLabels: ['Languages — EN · हिंदी · मराठी', 'Danger signs screened every message', 'Tools in one companion', 'Data that leaves your device'],
    demo: {
      eyebrow: 'Watch the demo',
      title: 'See PoshanMitra in action',
      sub: 'A quick, narrated tour of how Mitra guides you — day by day, with safety first. Tap play for the voice-over.',
      poster: 'Watch the demo',
      resume: 'Resume',
      replay: 'Replay demo',
      tourNote: '2-minute tour · with voice-over',
      caption0: 'A quick tour of how PoshanMitra helps you through pregnancy.',
      scenes: [
        { label: 'Meet Mitra', narration: 'Meet Mitra, your caring pregnancy companion. Ask anything about diet, health, or your baby — in English, Hindi, or Marathi.' },
        { label: 'Daily nutrition', narration: 'Each day, Mitra shares a sample meal plan for your trimester, using everyday Indian foods.' },
        { label: 'Government schemes', narration: 'See which government schemes you qualify for, like the Matru Vandana Yojana, in just a few taps.' },
        { label: 'Nearby hospitals', narration: 'Find maternity hospitals near you, with directions and one-tap calling.' },
        { label: 'Safety first', narration: 'And if you ever describe a danger sign, Mitra instantly shows an emergency screen with 108. Safety always comes first.' },
        { label: 'Start free', narration: 'PoshanMitra. Swasth Maa, Swasth Shishu, Swasth Bharat. Get started free today.' },
      ],
      mock: {
        mitra: 'Mitra', chatQ: "I'm in my 5th month. What should I eat today?",
        chatA: "Focus on iron and calcium — palak, dal, curd and a fruit. Here's a sample plan 🌸",
        mealTitle: "Today's meal plan", breakfast: 'Breakfast', lunch: 'Lunch', snack: 'Snack',
        b_food: 'Vegetable poha + milk', l_food: 'Roti, dal, palak sabzi, curd', s_food: 'Fruit + roasted chana',
        mealNote: 'Sample plan — general guidance for pregnancy.',
        schemeTitle: 'Scheme eligibility', eligible: '✓ You look eligible · ₹5,000 in instalments',
        jsyDesc: 'Cash help for institutional delivery',
        hospTitle: 'Nearby hospitals', hospMeta: 'Sahyadri Hospital · 1.2 km', call: 'Call',
        safeTitle: 'This may need urgent care', safeSub: 'Please contact a doctor or emergency services now.', call108: 'Call 108',
        getStartedFree: 'Get started free',
      },
    },
    featuresTitle: 'Everything a mother needs, in one place',
    featuresSub: "From the first trimester to your baby's first foods — practical, trustworthy help, always a doctor away.",
    features: [
      { title: 'Mitra, your AI companion', desc: 'Ask anything about pregnancy, diet or baby care in your own language. Mitra remembers your month and conditions like a caring friend.' },
      { title: 'Sample daily meal plans', desc: 'Balanced, vegetarian-friendly Indian meal ideas for each day — general guidance to eat well through pregnancy.' },
      { title: 'Government schemes', desc: 'PMMVY, JSY, PMSMA and more — with a simple eligibility checker that tells you what you qualify for.' },
      { title: 'Nearby hospitals', desc: 'A real map of maternity hospitals near you with directions and one-tap calling — no account, no API key.' },
      { title: 'Verified videos', desc: 'Short, trustworthy videos from credible health educators — in English and हिंदी — never unverified clips.' },
      { title: 'Health reports & trends', desc: 'Log Hb, BP, sugar and weight and see simple trends over time. A personal record you can share with your doctor.' },
      { title: 'Gentle reminders', desc: 'ANC visits, iron-folic tablets and custom nudges — with one-tap WhatsApp sharing for your family.' },
      { title: 'Health campaigns', desc: 'Stay on top of official drives like PMSMA and Poshan Maah, with what, when and where to go.' },
    ],
    safety: {
      eyebrow: 'Safety comes first',
      title: 'Designed to keep mother and baby safe',
      sub: 'Maternal health is not the place for guesswork. PoshanMitra is built conservatively — it screens for emergencies, refuses to diagnose, and always guides you toward care.',
      emergency: 'A danger sign in your message brings up an emergency screen with 108 right away — no chatbot delay.',
      items: [
        { title: 'Danger-sign detection', desc: 'Twelve obstetric warning signs are screened on every message. If one appears, Mitra shows an emergency screen with 108 — instantly, before anything else.' },
        { title: 'Information, never diagnosis', desc: 'Mitra shares guidance and always points you toward a doctor — never a diagnosis, medicine name or dose.' },
        { title: 'Your data stays with you', desc: 'Your profile and health logs live on your device. There is no account server collecting your information.' },
        { title: 'Built with clinical care', desc: 'Content is written conservatively for pregnancy safety, with a disclaimer on every screen. Not a substitute for your doctor.' },
      ],
    },
    how: {
      title: 'Start in under two minutes',
      sub: 'No paperwork, no cost. Just three simple steps.',
      steps: [
        { title: 'Sign in with your mobile', desc: 'No passwords, no paperwork. Just your phone number to get started.' },
        { title: 'Tell us about you', desc: 'Your due date, food preference and language — takes under a minute.' },
        { title: 'Get daily guidance', desc: 'A companion, a plan and reminders that adapt to your week of pregnancy.' },
      ],
    },
    langs: {
      eyebrow: 'In your language',
      title: 'English, हिंदी and मराठी',
      sub: 'Mitra chats, the diet plan, reminders and the whole app switch to your language. Made for Tier-2 and Tier-3 India, and light enough for everyday phones.',
      cards: [['English', 'Hello, Mitra'], ['हिंदी', 'नमस्ते, मित्रा'], ['मराठी', 'नमस्कार, मित्रा']],
    },
    priya: {
      eyebrow: 'An example journey',
      title: 'Meet Priya, 26 — Pune, 5th month',
      body: "Every morning Priya opens PoshanMitra to see her week's milestones, checks off her iron tablet, asks Mitra what to cook, and finds she's eligible for PMMVY. When she felt unwell one evening, Mitra recognised the warning sign and showed her the emergency screen at once. That's the companion we're building.",
    },
    cta: { title: 'Start your healthy pregnancy journey today', sub: 'Free during our private beta. Your data stays with you.' },
    footer: { noteTitle: 'A note on care', note: 'PoshanMitra provides general health information, not medical advice, and is not a substitute for your doctor. In an emergency, call 108.', product: 'Product', start: 'Get started', createProfile: 'Create profile' },
  },

  hi: {
    nav: { features: 'विशेषताएँ', safety: 'सुरक्षा', how: 'कैसे काम करता है', languages: 'भाषाएँ' },
    login: 'लॉग इन',
    getStarted: 'शुरू करें',
    getStartedFree: 'मुफ़्त शुरू करें',
    watchDemo: 'डेमो देखें',
    createProfile: 'अपनी मुफ़्त प्रोफ़ाइल बनाएँ',
    beta: 'हमारे प्राइवेट बीटा में मुफ़्त',
    heroTitle: 'आपकी गर्भावस्था के हर कदम पर एक भरोसेमंद',
    heroAccent: 'साथी',
    heroSub: 'पोषणमित्र AI भारत की गर्भवती माताओं का साथ देता है — एक दोस्ताना AI साथी, रोज़ का पोषण, सरकारी योजनाएँ, पास के अस्पताल और सुरक्षा-पहले देखभाल के साथ — अंग्रेज़ी, हिंदी और मराठी में।',
    trust: ['3 भाषाएँ', 'सुरक्षा-पहले डिज़ाइन', 'डेटा आपके फ़ोन पर ही रहता है'],
    statLabels: ['भाषाएँ — EN · हिंदी · मराठी', 'हर संदेश में खतरे के संकेत जाँचे जाते हैं', 'एक ही साथी में उपकरण', 'डेटा जो आपके फ़ोन से बाहर जाता है'],
    demo: {
      eyebrow: 'डेमो देखें',
      title: 'पोषणमित्र को काम करते देखें',
      sub: 'मित्रा रोज़ आपका साथ कैसे देती है — इसकी एक छोटी, आवाज़ वाली झलक, सुरक्षा को पहले रखते हुए। आवाज़ के लिए प्ले दबाएँ।',
      poster: 'डेमो देखें',
      resume: 'जारी रखें',
      replay: 'फिर से चलाएँ',
      tourNote: '2-मिनट की झलक · आवाज़ के साथ',
      caption0: 'पोषणमित्र गर्भावस्था में आपकी कैसे मदद करती है, इसकी एक छोटी झलक।',
      scenes: [
        { label: 'मित्रा से मिलें', narration: 'मिलिए मित्रा से, गर्भावस्था में आपकी देखभाल करने वाली साथी। आहार, सेहत या अपने शिशु के बारे में कुछ भी पूछें — अंग्रेज़ी, हिंदी या मराठी में।' },
        { label: 'रोज़ का पोषण', narration: 'हर दिन मित्रा आपकी तिमाही के अनुसार रोज़ के भारतीय खाने से एक नमूना भोजन योजना देती है।' },
        { label: 'सरकारी योजनाएँ', narration: 'कुछ ही टैप में देखें कि आप किन सरकारी योजनाओं के योग्य हैं, जैसे मातृ वंदना योजना।' },
        { label: 'पास के अस्पताल', narration: 'अपने पास के मातृत्व अस्पताल खोजें, रास्ते और एक-टैप कॉल के साथ।' },
        { label: 'सुरक्षा पहले', narration: 'और अगर आप कभी कोई खतरे का संकेत बताती हैं, तो मित्रा तुरंत 108 वाली आपातकालीन स्क्रीन दिखाती है। सुरक्षा हमेशा पहले।' },
        { label: 'मुफ़्त शुरू करें', narration: 'पोषणमित्र। स्वस्थ माँ, स्वस्थ शिशु, स्वस्थ भारत। आज ही मुफ़्त शुरू करें।' },
      ],
      mock: {
        mitra: 'मित्रा', chatQ: 'मैं पाँचवें महीने में हूँ। आज मुझे क्या खाना चाहिए?',
        chatA: 'आयरन और कैल्शियम पर ध्यान दें — पालक, दाल, दही और एक फल। यह रहा एक नमूना प्लान 🌸',
        mealTitle: 'आज की भोजन योजना', breakfast: 'नाश्ता', lunch: 'दोपहर का खाना', snack: 'हल्का नाश्ता',
        b_food: 'वेजिटेबल पोहा + दूध', l_food: 'रोटी, दाल, पालक सब्ज़ी, दही', s_food: 'फल + भुना चना',
        mealNote: 'नमूना प्लान — गर्भावस्था के लिए सामान्य मार्गदर्शन।',
        schemeTitle: 'योजना पात्रता', eligible: '✓ आप पात्र लगती हैं · ₹5,000 किश्तों में',
        jsyDesc: 'संस्थागत प्रसव के लिए नकद सहायता',
        hospTitle: 'पास के अस्पताल', hospMeta: 'सह्याद्री अस्पताल · 1.2 किमी', call: 'कॉल',
        safeTitle: 'इसमें तुरंत देखभाल की ज़रूरत हो सकती है', safeSub: 'कृपया अभी डॉक्टर या आपातकालीन सेवा से संपर्क करें।', call108: '108 पर कॉल करें',
        getStartedFree: 'मुफ़्त शुरू करें',
      },
    },
    featuresTitle: 'एक माँ को जो चाहिए, सब एक जगह',
    featuresSub: 'पहली तिमाही से लेकर शिशु के पहले आहार तक — व्यावहारिक, भरोसेमंद मदद, और डॉक्टर हमेशा एक कदम दूर।',
    features: [
      { title: 'मित्रा, आपकी AI साथी', desc: 'गर्भावस्था, आहार या शिशु की देखभाल के बारे में अपनी भाषा में कुछ भी पूछें। मित्रा आपके महीने और स्थिति को एक देखभाल करने वाली दोस्त की तरह याद रखती है।' },
      { title: 'रोज़ की नमूना भोजन योजना', desc: 'हर दिन के लिए संतुलित, शाकाहारी-अनुकूल भारतीय भोजन के सुझाव — गर्भावस्था में अच्छा खाने के लिए सामान्य मार्गदर्शन।' },
      { title: 'सरकारी योजनाएँ', desc: 'PMMVY, JSY, PMSMA और भी — एक आसान पात्रता जाँच के साथ जो बताती है आप किसके योग्य हैं।' },
      { title: 'पास के अस्पताल', desc: 'आपके पास के मातृत्व अस्पतालों का असली नक्शा, रास्ते और एक-टैप कॉल के साथ — कोई खाता नहीं, कोई API key नहीं।' },
      { title: 'सत्यापित वीडियो', desc: 'भरोसेमंद स्वास्थ्य शिक्षकों के छोटे वीडियो — अंग्रेज़ी और हिंदी में — कभी भी असत्यापित नहीं।' },
      { title: 'सेहत रिपोर्ट और रुझान', desc: 'Hb, BP, शुगर और वज़न दर्ज करें और समय के साथ रुझान देखें। एक निजी रिकॉर्ड जिसे आप डॉक्टर से साझा कर सकती हैं।' },
      { title: 'कोमल रिमाइंडर', desc: 'ANC विज़िट, आयरन-फोलिक गोलियाँ और अपने रिमाइंडर — परिवार के लिए एक-टैप WhatsApp साझा के साथ।' },
      { title: 'स्वास्थ्य अभियान', desc: 'PMSMA और पोषण माह जैसे आधिकारिक अभियानों की जानकारी — क्या, कब और कहाँ जाना है।' },
    ],
    safety: {
      eyebrow: 'सुरक्षा सबसे पहले',
      title: 'माँ और शिशु को सुरक्षित रखने के लिए बनाया गया',
      sub: 'मातृ स्वास्थ्य अनुमान लगाने की जगह नहीं है। पोषणमित्र सावधानी से बनाई गई है — यह आपात स्थिति जाँचती है, निदान नहीं करती, और हमेशा देखभाल की ओर मार्गदर्शन करती है।',
      emergency: 'आपके संदेश में कोई खतरे का संकेत तुरंत 108 वाली आपातकालीन स्क्रीन लाता है — कोई चैटबॉट देरी नहीं।',
      items: [
        { title: 'खतरे के संकेत की पहचान', desc: 'हर संदेश में बारह प्रसूति चेतावनी संकेत जाँचे जाते हैं। कोई दिखे तो मित्रा तुरंत, सबसे पहले, 108 वाली आपातकालीन स्क्रीन दिखाती है।' },
        { title: 'जानकारी, कभी निदान नहीं', desc: 'मित्रा मार्गदर्शन देती है और हमेशा डॉक्टर की ओर इशारा करती है — कभी कोई निदान, दवा का नाम या खुराक नहीं।' },
        { title: 'आपका डेटा आपके पास', desc: 'आपकी प्रोफ़ाइल और सेहत के रिकॉर्ड आपके फ़ोन पर रहते हैं। कोई खाता सर्वर आपकी जानकारी इकट्ठा नहीं करता।' },
        { title: 'चिकित्सकीय सावधानी से बना', desc: 'सामग्री गर्भावस्था सुरक्षा के लिए सावधानी से लिखी गई है, हर स्क्रीन पर एक अस्वीकरण के साथ। यह आपके डॉक्टर का विकल्प नहीं है।' },
      ],
    },
    how: {
      title: 'दो मिनट से भी कम में शुरू करें',
      sub: 'कोई कागज़ी काम नहीं, कोई खर्च नहीं। बस तीन आसान कदम।',
      steps: [
        { title: 'अपने मोबाइल से साइन इन करें', desc: 'कोई पासवर्ड नहीं, कोई कागज़ी काम नहीं। शुरू करने के लिए बस आपका फ़ोन नंबर।' },
        { title: 'हमें अपने बारे में बताएँ', desc: 'आपकी संभावित तारीख, भोजन पसंद और भाषा — एक मिनट से भी कम में।' },
        { title: 'रोज़ का मार्गदर्शन पाएँ', desc: 'एक साथी, एक योजना और रिमाइंडर जो आपके गर्भावस्था सप्ताह के अनुसार ढलते हैं।' },
      ],
    },
    langs: {
      eyebrow: 'आपकी भाषा में',
      title: 'अंग्रेज़ी, हिंदी और मराठी',
      sub: 'मित्रा की बातचीत, आहार योजना, रिमाइंडर और पूरा ऐप आपकी भाषा में बदल जाता है। टियर-2 और टियर-3 भारत के लिए बना, और रोज़मर्रा के फ़ोन के लिए हल्का।',
      cards: [['English', 'Hello, Mitra'], ['हिंदी', 'नमस्ते, मित्रा'], ['मराठी', 'नमस्कार, मित्रा']],
    },
    priya: {
      eyebrow: 'एक उदाहरण यात्रा',
      title: 'मिलिए प्रिया से, 26 — पुणे, पाँचवाँ महीना',
      body: 'हर सुबह प्रिया पोषणमित्र खोलती है ताकि अपने सप्ताह के पड़ाव देखे, अपनी आयरन गोली पर निशान लगाए, मित्रा से पूछे कि क्या पकाना है, और पाती है कि वह PMMVY के योग्य है। एक शाम जब उसे तबीयत ठीक नहीं लगी, मित्रा ने चेतावनी संकेत पहचाना और तुरंत आपातकालीन स्क्रीन दिखाई। यही साथी हम बना रहे हैं।',
    },
    cta: { title: 'आज ही अपनी स्वस्थ गर्भावस्था की यात्रा शुरू करें', sub: 'हमारे प्राइवेट बीटा में मुफ़्त। आपका डेटा आपके पास रहता है।' },
    footer: { noteTitle: 'देखभाल पर एक बात', note: 'पोषणमित्र सामान्य स्वास्थ्य जानकारी देती है, चिकित्सा सलाह नहीं, और यह आपके डॉक्टर का विकल्प नहीं है। आपात स्थिति में 108 पर कॉल करें।', product: 'उत्पाद', start: 'शुरू करें', createProfile: 'प्रोफ़ाइल बनाएँ' },
  },

  mr: {
    nav: { features: 'वैशिष्ट्ये', safety: 'सुरक्षा', how: 'कसे काम करते', languages: 'भाषा' },
    login: 'लॉग इन',
    getStarted: 'सुरू करा',
    getStartedFree: 'मोफत सुरू करा',
    watchDemo: 'डेमो पाहा',
    createProfile: 'तुमची मोफत प्रोफाइल तयार करा',
    beta: 'आमच्या प्रायव्हेट बीटामध्ये मोफत',
    heroTitle: 'तुमच्या गर्भधारणेच्या प्रत्येक टप्प्यावर एक विश्वासू',
    heroAccent: 'सोबती',
    heroSub: 'पोषणमित्र AI भारतातील गर्भवती मातांना साथ देते — एक मैत्रीपूर्ण AI सोबती, रोजचे पोषण, सरकारी योजना, जवळचे रुग्णालय आणि सुरक्षा-प्रथम काळजी यांसह — इंग्रजी, हिंदी आणि मराठीत.',
    trust: ['3 भाषा', 'सुरक्षा-प्रथम रचना', 'डेटा तुमच्या फोनवरच राहतो'],
    statLabels: ['भाषा — EN · हिंदी · मराठी', 'प्रत्येक संदेशात धोक्याची चिन्हे तपासली जातात', 'एकाच सोबतीत साधने', 'डेटा जो तुमच्या फोनबाहेर जातो'],
    demo: {
      eyebrow: 'डेमो पाहा',
      title: 'पोषणमित्र कृतीत पाहा',
      sub: 'मित्रा रोज तुम्हाला कशी साथ देते याची एक छोटी, आवाज असलेली झलक — सुरक्षेला प्रथम ठेवून. आवाजासाठी प्ले दाबा.',
      poster: 'डेमो पाहा',
      resume: 'सुरू ठेवा',
      replay: 'पुन्हा चालवा',
      tourNote: '2-मिनिटांची झलक · आवाजासह',
      caption0: 'पोषणमित्र गर्भधारणेत तुम्हाला कशी मदत करते याची एक छोटी झलक.',
      scenes: [
        { label: 'मित्राला भेटा', narration: 'भेटा मित्राला, गर्भधारणेत तुमची काळजी घेणारी सोबती. आहार, आरोग्य किंवा तुमच्या बाळाबद्दल काहीही विचारा — इंग्रजी, हिंदी किंवा मराठीत.' },
        { label: 'रोजचे पोषण', narration: 'दररोज मित्रा तुमच्या तिमाहीनुसार रोजच्या भारतीय पदार्थांतून एक नमुना आहार योजना देते.' },
        { label: 'सरकारी योजना', narration: 'काही टॅपमध्ये पाहा तुम्ही कोणत्या सरकारी योजनांसाठी पात्र आहात, जसे की मातृ वंदना योजना.' },
        { label: 'जवळचे रुग्णालय', narration: 'तुमच्या जवळची प्रसूती रुग्णालये शोधा, दिशा आणि एक-टॅप कॉलसह.' },
        { label: 'सुरक्षा प्रथम', narration: 'आणि जर तुम्ही कधी धोक्याचे चिन्ह सांगितले, तर मित्रा लगेच 108 असलेली आपत्कालीन स्क्रीन दाखवते. सुरक्षा नेहमी प्रथम.' },
        { label: 'मोफत सुरू करा', narration: 'पोषणमित्र. स्वस्थ माँ, स्वस्थ शिशु, स्वस्थ भारत. आजच मोफत सुरू करा.' },
      ],
      mock: {
        mitra: 'मित्रा', chatQ: 'मी पाचव्या महिन्यात आहे. आज मी काय खावे?',
        chatA: 'लोह आणि कॅल्शियमवर लक्ष द्या — पालक, डाळ, दही आणि एक फळ. ही रही एक नमुना योजना 🌸',
        mealTitle: 'आजची आहार योजना', breakfast: 'न्याहारी', lunch: 'दुपारचे जेवण', snack: 'हलका नाश्ता',
        b_food: 'भाजी पोहे + दूध', l_food: 'चपाती, डाळ, पालक भाजी, दही', s_food: 'फळ + भाजलेले हरभरे',
        mealNote: 'नमुना योजना — गर्भधारणेसाठी सर्वसाधारण मार्गदर्शन.',
        schemeTitle: 'योजना पात्रता', eligible: '✓ तुम्ही पात्र दिसता · ₹5,000 हप्त्यांमध्ये',
        jsyDesc: 'संस्थात्मक प्रसूतीसाठी रोख मदत',
        hospTitle: 'जवळचे रुग्णालय', hospMeta: 'सह्याद्री रुग्णालय · 1.2 किमी', call: 'कॉल',
        safeTitle: 'यासाठी तातडीने काळजी लागू शकते', safeSub: 'कृपया आत्ताच डॉक्टर किंवा आपत्कालीन सेवेशी संपर्क साधा.', call108: '108 वर कॉल करा',
        getStartedFree: 'मोफत सुरू करा',
      },
    },
    featuresTitle: 'एका आईला जे हवे, ते सर्व एका ठिकाणी',
    featuresSub: 'पहिल्या तिमाहीपासून बाळाच्या पहिल्या आहारापर्यंत — व्यावहारिक, विश्वासार्ह मदत, आणि डॉक्टर नेहमी एक पाऊल दूर.',
    features: [
      { title: 'मित्रा, तुमची AI सोबती', desc: 'गर्भधारणा, आहार किंवा बाळाच्या काळजीबद्दल तुमच्या भाषेत काहीही विचारा. मित्रा तुमचा महिना आणि स्थिती एका काळजी घेणाऱ्या मैत्रिणीसारखी लक्षात ठेवते.' },
      { title: 'रोजची नमुना आहार योजना', desc: 'प्रत्येक दिवसासाठी संतुलित, शाकाहारी-अनुकूल भारतीय आहाराचे सुचाव — गर्भधारणेत चांगले खाण्यासाठी सर्वसाधारण मार्गदर्शन.' },
      { title: 'सरकारी योजना', desc: 'PMMVY, JSY, PMSMA आणि आणखी — एका सोप्या पात्रता तपासणीसह जी सांगते तुम्ही कशासाठी पात्र आहात.' },
      { title: 'जवळचे रुग्णालय', desc: 'तुमच्या जवळच्या प्रसूती रुग्णालयांचा खरा नकाशा, दिशा आणि एक-टॅप कॉलसह — खाते नाही, API key नाही.' },
      { title: 'सत्यापित व्हिडिओ', desc: 'विश्वासार्ह आरोग्य शिक्षकांचे छोटे व्हिडिओ — इंग्रजी आणि हिंदीत — कधीही असत्यापित नाही.' },
      { title: 'आरोग्य अहवाल आणि कल', desc: 'Hb, BP, साखर आणि वजन नोंदवा आणि कालांतराने कल पाहा. एक वैयक्तिक नोंद जी तुम्ही डॉक्टरांशी सामायिक करू शकता.' },
      { title: 'सौम्य स्मरणपत्रे', desc: 'ANC भेटी, लोह-फॉलिक गोळ्या आणि तुमची स्मरणपत्रे — कुटुंबासाठी एक-टॅप WhatsApp सामायिकरणासह.' },
      { title: 'आरोग्य मोहिमा', desc: 'PMSMA आणि पोषण माह यांसारख्या अधिकृत मोहिमांची माहिती — काय, कधी आणि कुठे जायचे.' },
    ],
    safety: {
      eyebrow: 'सुरक्षा सर्वात आधी',
      title: 'आई आणि बाळाला सुरक्षित ठेवण्यासाठी बनवलेले',
      sub: 'मातृ आरोग्य ही अंदाज लावण्याची जागा नाही. पोषणमित्र काळजीपूर्वक बनवली आहे — ती आपत्कालीन स्थिती तपासते, निदान करत नाही, आणि नेहमी काळजीकडे मार्गदर्शन करते.',
      emergency: 'तुमच्या संदेशातील धोक्याचे चिन्ह लगेच 108 असलेली आपत्कालीन स्क्रीन आणते — चॅटबॉट विलंब नाही.',
      items: [
        { title: 'धोक्याच्या चिन्हांची ओळख', desc: 'प्रत्येक संदेशात बारा प्रसूती इशारा चिन्हे तपासली जातात. एखादे दिसल्यास मित्रा लगेच, सर्वात आधी, 108 असलेली आपत्कालीन स्क्रीन दाखवते.' },
        { title: 'माहिती, कधीही निदान नाही', desc: 'मित्रा मार्गदर्शन देते आणि नेहमी डॉक्टरांकडे निर्देश करते — कधीही निदान, औषधाचे नाव किंवा मात्रा नाही.' },
        { title: 'तुमचा डेटा तुमच्याजवळ', desc: 'तुमची प्रोफाइल आणि आरोग्य नोंदी तुमच्या फोनवर राहतात. कोणताही खाते सर्व्हर तुमची माहिती गोळा करत नाही.' },
        { title: 'वैद्यकीय काळजीने बनवलेले', desc: 'मजकूर गर्भधारणा सुरक्षेसाठी काळजीपूर्वक लिहिला आहे, प्रत्येक स्क्रीनवर अस्वीकरणासह. हे तुमच्या डॉक्टरांचा पर्याय नाही.' },
      ],
    },
    how: {
      title: 'दोन मिनिटांपेक्षा कमी वेळात सुरू करा',
      sub: 'कागदपत्रे नाहीत, खर्च नाही. फक्त तीन सोप्या पायऱ्या.',
      steps: [
        { title: 'तुमच्या मोबाइलने साइन इन करा', desc: 'पासवर्ड नाही, कागदपत्रे नाहीत. सुरू करण्यासाठी फक्त तुमचा फोन नंबर.' },
        { title: 'आम्हाला तुमच्याबद्दल सांगा', desc: 'तुमची संभाव्य तारीख, आहार पसंती आणि भाषा — एका मिनिटापेक्षा कमी वेळात.' },
        { title: 'रोजचे मार्गदर्शन मिळवा', desc: 'एक सोबती, एक योजना आणि स्मरणपत्रे जी तुमच्या गर्भधारणेच्या आठवड्यानुसार जुळवून घेतात.' },
      ],
    },
    langs: {
      eyebrow: 'तुमच्या भाषेत',
      title: 'इंग्रजी, हिंदी आणि मराठी',
      sub: 'मित्राची बातचीत, आहार योजना, स्मरणपत्रे आणि संपूर्ण अ‍ॅप तुमच्या भाषेत बदलते. टियर-2 आणि टियर-3 भारतासाठी बनवलेले, आणि रोजच्या फोनसाठी हलके.',
      cards: [['English', 'Hello, Mitra'], ['हिंदी', 'नमस्ते, मित्रा'], ['मराठी', 'नमस्कार, मित्रा']],
    },
    priya: {
      eyebrow: 'एक उदाहरण प्रवास',
      title: 'भेटा प्रियाला, 26 — पुणे, पाचवा महिना',
      body: 'दररोज सकाळी प्रिया पोषणमित्र उघडते, तिच्या आठवड्याचे टप्पे पाहते, तिची लोह गोळी नोंदवते, मित्राला काय शिजवायचे विचारते, आणि तिला कळते की ती PMMVY साठी पात्र आहे. एका संध्याकाळी तिला बरे वाटत नव्हते, तेव्हा मित्राने इशारा चिन्ह ओळखले आणि लगेच आपत्कालीन स्क्रीन दाखवली. हीच सोबती आम्ही घडवत आहोत.',
    },
    cta: { title: 'आजच तुमचा निरोगी गर्भधारणेचा प्रवास सुरू करा', sub: 'आमच्या प्रायव्हेट बीटामध्ये मोफत. तुमचा डेटा तुमच्याजवळ राहतो.' },
    footer: { noteTitle: 'काळजीबद्दल एक शब्द', note: 'पोषणमित्र सर्वसाधारण आरोग्य माहिती देते, वैद्यकीय सल्ला नाही, आणि हे तुमच्या डॉक्टरांचा पर्याय नाही. आपत्कालीन स्थितीत 108 वर कॉल करा.', product: 'उत्पादन', start: 'सुरू करा', createProfile: 'प्रोफाइल तयार करा' },
  },
}

export function getLanding(lang) {
  return LANDING[lang] || LANDING.en
}
