import { useMemo, useRef, useState } from 'react'
import { Link } from 'react-router-dom'
import { Plus, Trash2, TrendingUp, TrendingDown, Minus, Activity, MessageSquare, Info, Share2, Upload, Loader2, Check, Sparkles, Printer } from 'lucide-react'
import { PageHeader } from '../components/ui/PageHeader.jsx'
import { Button } from '../components/ui/Button.jsx'
import { Modal } from '../components/ui/Modal.jsx'
import { EmptyState } from '../components/ui/EmptyState.jsx'
import { TrendChart } from '../components/TrendChart.jsx'
import { storage } from '../lib/storage.js'
import { useT } from '../lib/i18n.js'
import { formatIN } from '../lib/dates.js'
import { useProfile } from '../context/ProfileContext.jsx'
import { shareOnWhatsApp } from '../lib/whatsapp.js'
import { isImageFile, readAndDownscaleImage } from '../lib/image.js'
import { extractReport, hasGeminiKey } from '../lib/gemini.js'
import {
  METRICS,
  getMetric,
  seriesFor,
  latestFor,
  trendFor,
  displayValue,
  plotValue,
  makeReading,
  addReading,
  removeReading,
  readingsFromExtract,
  isValidReading,
  todayISO,
} from '../lib/reports.js'

export function Reports() {
  const t = useT()
  const { lang } = useProfile()
  const [reports, setReports] = useState(() => storage.getReports())
  const [adding, setAdding] = useState(null) // metric key or null
  const [uploading, setUploading] = useState(false)

  function persist(next) {
    setReports(next)
    storage.setReports(next)
  }

  function handleAdd(metricKey, values, extra) {
    const reading = makeReading(metricKey, values, extra)
    if (!reading) return false
    persist(addReading(reports, reading))
    setAdding(null)
    return true
  }

  function handleDelete(id) {
    persist(removeReading(reports, id))
  }

  function handleSaveMany(readings) {
    if (!readings?.length) return
    let next = reports
    for (const r of readings) next = addReading(next, r)
    persist(next)
    setUploading(false)
  }

  const recent = useMemo(
    () =>
      reports
        .slice()
        .sort((a, b) => (a.date < b.date ? 1 : a.date > b.date ? -1 : 0))
        .slice(0, 12),
    [reports]
  )

  const hasAny = reports.length > 0

  function shareLatest() {
    const lines = METRICS.map((m) => {
      const latest = latestFor(reports, m.key)
      return latest ? `${t(`reports.metric.${m.key}`)}: ${displayValue(latest)} ${m.unit} (${formatIN(latest.date, lang)})` : null
    }).filter(Boolean)
    if (lines.length === 0) return
    shareOnWhatsApp(`${t('reports.title')}\n${lines.join('\n')}`)
  }

  // Export a clean, printable record she can save as a PDF or show at her clinic.
  // Uses the browser's own print dialog (no library, $0). Her own record — the sheet
  // itself states it is not a diagnosis.
  function downloadPdf() {
    if (!hasAny) return
    const w = window.open('', '_blank')
    if (!w) return
    const sections = METRICS.map((m) => {
      const series = seriesFor(reports, m.key).slice().reverse()
      if (!series.length) return ''
      const rows = series
        .map((r) => `<tr><td>${formatIN(r.date, lang)}</td><td>${displayValue(r)} ${m.unit}</td></tr>`)
        .join('')
      return `<h2>${t(`reports.metric.${m.key}`)}</h2><table><thead><tr><th>Date</th><th>Reading</th></tr></thead><tbody>${rows}</tbody></table>`
    }).join('')
    const name = profile?.name ? ` — ${profile.name}` : ''
    w.document.write(
      `<html><head><title>My Health Record</title><style>
        body{font-family:system-ui,sans-serif;max-width:720px;margin:36px auto;padding:0 24px;color:#1f2937}
        h1{color:#4F46E5;margin-bottom:2px} .sub{color:#6b7280;font-size:13px;margin-top:0}
        h2{font-size:15px;margin:22px 0 6px} table{width:100%;border-collapse:collapse;font-size:13px}
        th,td{text-align:left;border:1px solid #e5e7eb;padding:6px 10px} th{background:#f9fafb}
        .note{margin-top:28px;color:#6b7280;font-size:12px;border-top:1px solid #e5e7eb;padding-top:12px}
      </style></head><body>
        <h1>My Health Record${name}</h1>
        <p class="sub">Generated by PoshanMitra on ${formatIN(todayISO(), lang)}</p>
        ${sections}
        <p class="note">This is my own record of readings I noted down. It is not a medical test result or a diagnosis. Please read it together with my doctor.</p>
      </body></html>`
    )
    w.document.close()
    w.focus()
    w.print()
  }

  return (
    <>
      <PageHeader
        title={t('reports.title')}
        subtitle={t('reports.sub')}
        action={
          <div className="flex items-center gap-2 flex-wrap">
            <Button onClick={() => setUploading(true)}>
              <Upload size={15} /> Upload report
            </Button>
            {hasAny && (
              <Button variant="secondary" onClick={shareLatest}>
                <Share2 size={15} /> {t('common.whatsapp')}
              </Button>
            )}
            {hasAny && (
              <Button variant="secondary" onClick={downloadPdf}>
                <Printer size={15} /> PDF
              </Button>
            )}
            <Button as={Link} to="/chat?q=I%20want%20to%20understand%20my%20health%20readings" variant="secondary">
              <MessageSquare size={15} /> {t('common.askMitra')}
            </Button>
          </div>
        }
      />

      {/* Non-dismissable safety note — this is a personal record, not advice. */}
      <div className="mb-6 flex items-start gap-2 rounded-2xl border border-line bg-white shadow-card px-4 py-3 text-sm text-ink-muted">
        <Info size={16} className="shrink-0 text-indigo-500 mt-0.5" />
        <span>{t('reports.disclaimer')}</span>
      </div>

      {/* Metric cards */}
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
        {METRICS.map((m) => {
          const latest = latestFor(reports, m.key)
          const series = seriesFor(reports, m.key)
          const trend = trendFor(reports, m.key)
          const points = series.map((r) => ({
            x: r.date,
            y: plotValue(r),
            label: displayValue(r),
          }))
          return (
            <div key={m.key} className="rounded-2xl bg-white border border-line shadow-card p-5">
              <div className="flex items-start justify-between gap-3">
                <div className="flex items-center gap-2.5">
                  <span
                    className="w-9 h-9 rounded-2xl flex items-center justify-center shrink-0"
                    style={{ backgroundColor: m.tint }}
                  >
                    <Activity size={18} color={m.color} />
                  </span>
                  <div>
                    <h3 className="text-sm font-semibold text-ink">{t(`reports.metric.${m.key}`)}</h3>
                    <p className="text-xs text-ink-faint">{m.unit}</p>
                  </div>
                </div>
                <button
                  onClick={() => setAdding(m.key)}
                  className="inline-flex items-center gap-1 rounded-full border border-line px-2.5 py-1 text-xs font-medium text-indigo-600 hover:bg-indigo-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-indigo-500"
                >
                  <Plus size={13} /> {t('reports.add')}
                </button>
              </div>

              <div className="mt-3 flex items-end justify-between gap-2">
                <div>
                  <p className="text-[26px] leading-tight font-bold text-ink">
                    {latest ? displayValue(latest) : '—'}
                  </p>
                  {latest && (
                    <p className="text-xs text-ink-faint">
                      {formatIN(latest.date, lang)}
                    </p>
                  )}
                </div>
                {trend && (
                  <span className="inline-flex items-center gap-1 text-xs text-ink-muted">
                    {trend === 'up' ? (
                      <TrendingUp size={15} className="text-ink-muted" />
                    ) : trend === 'down' ? (
                      <TrendingDown size={15} className="text-ink-muted" />
                    ) : (
                      <Minus size={15} className="text-ink-muted" />
                    )}
                    {t(`reports.trend.${trend}`)}
                  </span>
                )}
              </div>

              <div className="mt-2">
                {points.length > 0 ? (
                  <TrendChart
                    points={points}
                    color={m.color}
                    unit={m.unit}
                    ariaLabel={`${t(`reports.metric.${m.key}`)}: ${points.length} readings, latest ${displayValue(latest)} ${m.unit}`}
                  />
                ) : (
                  <p className="text-xs text-ink-faint py-6 text-center">{t('reports.noneYet')}</p>
                )}
              </div>
            </div>
          )
        })}
      </div>

      {/* Recent entries */}
      <section className="mt-8 rounded-2xl bg-white border border-line shadow-card p-5">
        <h2 className="text-base font-semibold text-ink mb-3">{t('reports.recent')}</h2>
        {!hasAny ? (
          <EmptyState title={t('reports.empty')} />
        ) : (
          <ul className="divide-y divide-line">
            {recent.map((r) => {
              const m = getMetric(r.metric)
              return (
                <li key={r.id} className="flex items-center justify-between gap-3 py-2.5">
                  <div className="flex items-center gap-3 min-w-0">
                    <span
                      className="w-2.5 h-2.5 rounded-full shrink-0"
                      style={{ backgroundColor: m?.color || '#4F46E5' }}
                    />
                    <div className="min-w-0">
                      <p className="text-sm font-medium text-ink truncate">
                        {t(`reports.metric.${r.metric}`)}:{' '}
                        <span className="font-semibold">{displayValue(r)}</span>{' '}
                        <span className="text-ink-faint font-normal">{m?.unit}</span>
                      </p>
                      <p className="text-xs text-ink-faint">
                        {formatIN(r.date, lang)}
                        {r.note ? ` · ${r.note}` : ''}
                      </p>
                    </div>
                  </div>
                  <button
                    onClick={() => handleDelete(r.id)}
                    aria-label={t('reports.delete')}
                    className="p-1.5 rounded-lg text-ink-faint hover:text-red-600 hover:bg-red-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-red-400"
                  >
                    <Trash2 size={15} />
                  </button>
                </li>
              )
            })}
          </ul>
        )}
      </section>

      {adding && (
        <AddReadingModal
          metricKey={adding}
          onClose={() => setAdding(null)}
          onSave={handleAdd}
        />
      )}

      {uploading && <UploadReportModal onClose={() => setUploading(false)} onSave={handleSaveMany} />}
    </>
  )
}

// Upload a photo of a lab / ANC report → Gemini reads the printed values → the
// woman confirms them → they're added to her log. SAFETY: this is extraction into
// HER OWN record, clearly labelled "not a diagnosis"; nothing here interprets the
// values, and Mitra's rules are unchanged.
function UploadReportModal({ onClose, onSave }) {
  const t = useT()
  const { lang } = useProfile()
  const inputRef = useRef(null)
  const [preview, setPreview] = useState(null)
  const [stage, setStage] = useState('pick') // pick | extracting | review | error
  const [readings, setReadings] = useState([])
  const [other, setOther] = useState([])
  const [err, setErr] = useState('')

  async function onFile(e) {
    const file = e.target.files?.[0]
    if (!file) return
    setErr('')
    if (!isImageFile(file)) {
      setErr('Please choose a photo (JPG or PNG) of your report.')
      return
    }
    try {
      const img = await readAndDownscaleImage(file, 1024)
      setPreview(img.dataUrl)
      if (!hasGeminiKey()) {
        setErr('AI reading isn’t available right now. You can close this and add readings manually.')
        setStage('error')
        return
      }
      setStage('extracting')
      const { data, error } = await extractReport({ image: { data: img.base64, mimeType: img.mimeType } })
      if (error || !data) {
        setErr('Couldn’t read the values from this photo. Try a clearer, well-lit photo — or add them manually.')
        setStage('error')
        return
      }
      const mapped = readingsFromExtract(data).map((r) => ({ ...r, include: true }))
      setReadings(mapped)
      setOther(Array.isArray(data.other) ? data.other.filter((o) => o && o.name).slice(0, 6) : [])
      setStage(mapped.length || (data.other && data.other.length) ? 'review' : 'error')
      if (!mapped.length && !(data.other && data.other.length)) {
        setErr('No clear readings found. Try a sharper photo, or add them manually.')
      }
    } catch {
      setErr('Couldn’t read that image. Please try another photo.')
      setStage('error')
    }
  }

  function toggle(id) {
    setReadings((rs) => rs.map((r) => (r.id === id ? { ...r, include: !r.include } : r)))
  }

  function save() {
    onSave(readings.filter((r) => r.include).map(({ include, ...r }) => r))
  }

  const chosen = readings.filter((r) => r.include).length

  return (
    <Modal open onClose={onClose} title="Upload a report">
      <input ref={inputRef} type="file" accept="image/*" capture="environment" onChange={onFile} className="hidden" />

      {stage === 'pick' && (
        <div className="text-center">
          <button
            onClick={() => inputRef.current?.click()}
            className="w-full rounded-2xl border-2 border-dashed border-line bg-canvas py-10 px-4 flex flex-col items-center gap-3 hover:border-indigo-300 hover:bg-indigo-50/40 transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-indigo-500"
          >
            <span className="inline-flex items-center justify-center w-12 h-12 rounded-2xl bg-indigo-50">
              <Upload size={22} className="text-indigo-600" />
            </span>
            <span className="text-sm font-medium text-ink">Choose a photo of your lab or ANC report</span>
            <span className="text-xs text-ink-faint">Mitra will read the numbers so you don’t have to type them.</span>
          </button>
          {err && <p className="mt-3 text-xs text-red-600">{err}</p>}
          <p className="mt-3 text-[11px] text-ink-faint inline-flex items-center gap-1 justify-center">
            <Sparkles size={12} className="text-indigo-500" /> AI reads the printed values. Always confirm them — this is your record, not a diagnosis.
          </p>
        </div>
      )}

      {stage === 'extracting' && (
        <div className="text-center py-6">
          {preview && <img src={preview} alt="" className="mx-auto max-h-40 rounded-xl border border-line mb-4" />}
          <p className="inline-flex items-center gap-2 text-sm text-ink-muted">
            <Loader2 size={16} className="animate-spin text-indigo-600" /> Reading your report…
          </p>
        </div>
      )}

      {stage === 'review' && (
        <div className="space-y-4">
          <div className="flex items-start gap-3">
            {preview && <img src={preview} alt="" className="w-20 h-20 object-cover rounded-xl border border-line shrink-0" />}
            <p className="text-xs text-ink-muted">
              We read these values off your report. Please check they’re correct, then save the ones you want. This is your personal record — <span className="font-medium text-ink">not a diagnosis</span>.
            </p>
          </div>

          {readings.length > 0 ? (
            <ul className="space-y-2">
              {readings.map((r) => {
                const m = getMetric(r.metric)
                return (
                  <li key={r.id}>
                    <label className="flex items-center justify-between gap-3 rounded-xl border border-line bg-canvas px-3 py-2.5 cursor-pointer">
                      <span className="flex items-center gap-2.5">
                        <input type="checkbox" checked={r.include} onChange={() => toggle(r.id)} className="w-4 h-4 accent-indigo-600" />
                        <span className="text-sm text-ink">{t(`reports.metric.${r.metric}`)}</span>
                      </span>
                      <span className="text-sm font-semibold text-ink">
                        {displayValue(r)} <span className="text-ink-faint font-normal">{m?.unit}</span>
                        <span className="ml-2 text-xs text-ink-faint font-normal">{formatIN(r.date, lang)}</span>
                      </span>
                    </label>
                  </li>
                )
              })}
            </ul>
          ) : (
            <p className="text-sm text-ink-muted">No chartable readings found, but here’s what we saw:</p>
          )}

          {other.length > 0 && (
            <div className="rounded-xl bg-canvas border border-line px-3 py-2.5">
              <p className="text-[11px] font-semibold text-ink-muted mb-1">Other results read (not charted):</p>
              <ul className="text-xs text-ink-muted space-y-0.5">
                {other.map((o, i) => (
                  <li key={i}>{o.name}: <span className="text-ink">{o.value}</span></li>
                ))}
              </ul>
            </div>
          )}

          <div className="flex items-center gap-3 pt-1">
            <Button onClick={save} disabled={chosen === 0}>
              <Check size={16} /> Save {chosen > 0 ? chosen : ''} to my log
            </Button>
            <Button variant="ghost" onClick={onClose}>Cancel</Button>
          </div>
        </div>
      )}

      {stage === 'error' && (
        <div className="text-center py-4">
          {preview && <img src={preview} alt="" className="mx-auto max-h-32 rounded-xl border border-line mb-3" />}
          <p className="text-sm text-ink-muted">{err}</p>
          <div className="mt-4 flex items-center justify-center gap-2">
            <Button variant="secondary" onClick={() => { setStage('pick'); setErr(''); setPreview(null) }}>Try another photo</Button>
            <Button variant="ghost" onClick={onClose}>Close</Button>
          </div>
        </div>
      )}
    </Modal>
  )
}

function AddReadingModal({ metricKey, onClose, onSave }) {
  const t = useT()
  const metric = getMetric(metricKey)
  const [values, setValues] = useState({})
  const [date, setDate] = useState(todayISO())
  const [note, setNote] = useState('')

  const ok = isValidReading(metricKey, values) && date && date <= todayISO()

  function submit(e) {
    e.preventDefault()
    if (!ok) return
    onSave(metricKey, values, { date, note })
  }

  return (
    <Modal open onClose={onClose} title={`${t('reports.addTitle')} — ${t(`reports.metric.${metricKey}`)}`}>
      <form onSubmit={submit} className="space-y-4">
        <div className="grid grid-cols-2 gap-3">
          {metric.fields.map((f) => (
            <label key={f.name} className="block">
              <span className="text-[13px] font-medium text-ink mb-1.5 block">
                {t(`reports.field.${metricKey}.${f.name}`)} <span className="text-ink-faint">({metric.unit})</span>
              </span>
              <input
                type="number"
                inputMode="decimal"
                step={f.step}
                min={f.min}
                max={f.max}
                value={values[f.name] ?? ''}
                onChange={(e) => setValues((v) => ({ ...v, [f.name]: e.target.value }))}
                className="w-full rounded-xl border border-line bg-canvas px-3 py-2.5 text-sm focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-indigo-500"
              />
            </label>
          ))}
        </div>

        <label className="block">
          <span className="text-[13px] font-medium text-ink mb-1.5 block">{t('reports.date')}</span>
          <input
            type="date"
            value={date}
            max={todayISO()}
            onChange={(e) => setDate(e.target.value)}
            className="w-full rounded-xl border border-line bg-canvas px-3 py-2.5 text-sm focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-indigo-500"
          />
        </label>

        <label className="block">
          <span className="text-[13px] font-medium text-ink mb-1.5 block">
            {t('reports.note')} <span className="text-ink-faint">({t('reports.optional')})</span>
          </span>
          <input
            value={note}
            maxLength={140}
            onChange={(e) => setNote(e.target.value)}
            placeholder={t('reports.notePlaceholder')}
            className="w-full rounded-xl border border-line bg-canvas px-3 py-2.5 text-sm focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-indigo-500"
          />
        </label>

        <div className="flex items-center gap-3 pt-1">
          <Button type="submit" disabled={!ok}>
            {t('reports.save')}
          </Button>
          <Button type="button" variant="ghost" onClick={onClose}>
            {t('reports.cancel')}
          </Button>
        </div>
      </form>
    </Modal>
  )
}
